apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: discord-clone-mongodb-atlas-secrets
  namespace: discord-backend
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "mongodbatlas/credentials"
        objectType: "secretsmanager"
